[package]
name = "llm-traits"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"


[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }